environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\ci\\appveyor\\run_with_env.cmd"
    ARCH: "64"
    PYTHON: "C:\\Miniconda3-x64"

  matrix:
    - CONDA_PY: "36"
      CONDA_NUMPY: "114"

    - CONDA_PY: "37"
      CONDA_NUMPY: "115"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%;"
  - conda install conda-build -yq -c defaults
  # Build the compiled extension and run the project tests
  - conda build -c conda-forge -q tools/conda-recipe --numpy=%CONDA_NUMPY%"

build: false
