package:
  name: msmtools
  #version: {{ GIT_DESCRIBE_TAG[1:] + '+' + GIT_DESCRIBE_NUMBER + '.' + GIT_DESCRIBE_HASH}}
  version: 0

source:
  path: ../..

build:
  # this method tests the "installability" of the source distribution
  script: python setup.py sdist; pip install --no-deps --ignore-installed -v dist/* # [linux]
  #script: LDSHARED="$CC -shared" python setup.py install --single-version-externally-managed --record record.txt # [osx or linux]
  script: python setup.py install --single-version-externally-managed --record record.txt # [win]

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - cython
    - {{ pin_compatible('numpy') }}
    - python
    - setuptools
    - pip

  run:
    - decorator
    - numpy
    - python
    - scipy
    - setuptools

test:
  source_files:
    - tests/
  requires:
    - pytest
    - pytest-cov

about:
  home: http://github.com/markovmodel/msmtools
  license: LGPLv3+
  summary: "MSMTools"
